### ISSUE TITLE
i can't find where to transmit  the props "isNew"  in  EditContact component

### ISSUE THREAD

**Issue by xu-snow** [contacts-mvc/mobx-react-typescript#9]
`  <Route path='new' component={EditContact} />`
in this code,i can find "isNew"  to transmit

`export class EditContact extends Component<{appState?: AppState, isNew?: boolean}, {}>`
but in actually,this,props.isNew will used in this component

can you tell me where is missing

**Comment by mohsen1** [comment]
```
<Route path='new' component={() => <EditContact isNew={true} />} />
```
